Algoritmo "lista208"

Var
altura : real
sexo : caractere
peso : real
Inicio
escreva("informe seu sexo(masculino ou feminino): ")
leia(sexo)
escreva("informe sua altura: ")
leia(altura)
se sexo = ("masculino") entao
peso<-72.7*altura-58
escreval("Seu peso ideal é: ", peso, " KG")
fimse
se sexo = ("feminino") entao
peso<-72.7*altura-58
escreval("seu peso ideal é: ", peso, " KG")
fimse

Fimalgoritmo